// leave off @2x/@3x
const images = {
  logo: require('../Images/ir.png'),
  clearLogo: require('../Images/top_logo.png'),
  launch: require('../Images/launch-icon.png'),
  ready: require('../Images/your-app.png'),
  ignite: require('../Images/ignite_logo.png'),
  igniteClear: require('../Images/ignite-logo-transparent.png'),
  tileBg: require('../Images/tile_bg.png'),
  background: require('../Images/BG.png'),
  buttonBackground: require('../Images/button-bg.png'),
  api: require('../Images/Icons/icon-api-testing.png'),
  components: require('../Images/Icons/icon-components.png'),
  deviceInfo: require('../Images/Icons/icon-device-information.png'),
  faq: require('../Images/Icons/faq-icon.png'),
  home: require('../Images/Icons/icon-home.png'),
  theme: require('../Images/Icons/icon-theme.png'),
  usageExamples: require('../Images/Icons/icon-usage-examples.png'),
  chevronRight: require('../Images/Icons/chevron-right.png'),
  hamburger: require('../Images/Icons/hamburger.png'),
  backButton: require('../Images/Icons/back-button.png'),
  closeButton: require('../Images/Icons/close-button.png'),
  defaultAvatar: require('../Images/avatar.png'),
  instagram: require('../Images/instagram.png'),
  facebook: require('../Images/facebook.png'),
  snapchat: require('../Images/snapchat.png'),
  pinterest: require('../Images/pinterest.png'),
  youtube: require('../Images/youtube.png'),
  twitter: require('../Images/twitter.png'),
  buddyLogo: require('../Images/buddyLogo.png'),
  mapImage: require('../Images/mapimage.png'),
  airplane: require('../Images/airplane.png'),
  bottleWithPopping: require('../Images/bottle-with-popping.png'),
  cameraWithFlash: require('../Images/camera-with-flash.png'),
  clinkingBeerMugs: require('../Images/clinking-beer-mugs.png'),
  crystalBall: require('../Images/crystal-ball.png'),
  dancer: require('../Images/dancer.png'),
  dancerEmojiModifierFitzpatrickType: require('../Images/dancer_emoji-modifier-fitzpatrick-type.png'),
  faceWithPartyHornAndPartyHat: require('../Images/face-with-party-horn-and-party-hat.png'),
  manDancing: require('../Images/man-dancing.png'),
  partyPopper: require('../Images/party-popper.png'),
  pushpin: require('../Images/pushpin.png'),
  speakerWithOneSoundWave: require('../Images/speaker-with-one-sound-wave.png'),
  speakerWithThreeSoundWaves: require('../Images/speaker-with-three-sound-waves.png'),
  thumbsUpSign: require('../Images/thumbs-up-sign.png'),
  BluecommentBubble: require('../Images/Bluecommentbubble.png'),
  Colorfulbar: require('../Images/Colorfulbar.png'),
  blue_white_clock: require('../Images/blue_white_clock.png'),
  White_eyeball: require('../Images/White_eyeball.png'),
}

export default images
